global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['app:5000']
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']