apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    user: ${POSTGRES_USER}    
    secureJsonData:
      password: ${POSTGRES_PASSWORD}      
    jsonData:    
      database: ${POSTGRES_DB}
      sslmode: 'disable'
      timescaledb: true
      postgresVersion: 1500